name: meetup
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  basic_utils: ^2.5.3
  cached_network_image: ^2.2.0+1
  clipboard: ^0.1.2+8
  cool_alert: ^1.0.1
  dartx: ^0.5.0
  dio: ^3.0.10
  dio_http_cache: ^0.2.11
  firebase_admob: ^0.11.0+1
  firebase_auth: ^0.20.0+1
  firebase_core: ^0.7.0
  firebase_messaging: ^8.0.0-dev.14
  flag: ^3.1.0
  flutter_icons: ^1.0.0+1
  flutter_local_notifications: ^3.0.2
  flutter_onboard: ^0.1.0
  google_fonts: ^0.4.0
  google_nav_bar: ^3.1.0
  i18n_extension: ^4.0.0
  image_picker: ^0.6.7+17
  in_app_review: ^1.0.4
  intl: ^0.16.0
  jitsi_meet: ^2.0.0
  line_icons: ^0.2.0
  package_info: ^0.4.3+2
  pin_code_fields: ^6.1.0
  provider: ^4.3.2+3
  pull_to_refresh: ^1.6.4
  random_string: ^2.1.0
  share: ^0.6.5+4
  shared_preferences: ^0.5.10
  stacked: ^1.7.6
  url_launcher: ^5.5.0
  velocity_x: ^2.6.0

dependency_overrides:
  flutter_svg: ^0.19.3
  intl: ^0.17.0-nullsafety.2
  args: ^2.0.0
  flutter_application_id: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: '^0.8.0'
  flutter_native_splash: ^0.1.9

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/images/app_icon.png'

flutter_native_splash:
  image: assets/images/app_icon.png
  color: '20063B'

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
